version: 2

sources:
  - name: raw
    schema: gwz_raw_data
    tables:
      - name: sales
        identifier: raw_gwz_sales
        description: Sales of Greenweez. We have one row per `product_id` found in each `orders_id`.
        columns:
          - name: date_date
            description: Date of purchase.
          - name: orders_id
            description: Foreign key to the shipping data.
          - name: pdt_id
            description: Foreign key to the product.
          - name: revenue
            description: The amount paid by the customer to purchase the product. Revenue = quantity * selling_price.
          - name: quantity
            description: The quantity of products purchased for a given order.
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: products
        identifier: raw_gz_product
        description: Products of Greenweez.
        columns:
          - name: products_id
            description: Primary key.
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: The purchase price of the product.

      - name: ship
        identifier: raw_gz_ship
        description: Shipping data for Greenweez orders.
        columns:
          - name: orders_id
            description: Primary key.
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: The price the customer pays for shipping.
          - name: log_cost
            description: The cost of preparing the parcel in the distribution center/warehouse.
          - name: ship_cost
            description: Shipping cost paid by Greenweez to the carrier/logistics provider.

models:
  - name: stg_raw_product
  - name: stg_raw_sales
  - name: stg_raw_ship

  - name: int_sales_margin
    description: Margin calculation per order line / product sale.
    columns:
      - name: margin
        description: Margin = Revenue - Purchase_cost.
      - name: purchase_cost
        description: Purchase_cost = Quantity * Purchase_price.

  - name: int_orders_margin
    description: Margin calculation per order.
    columns:
      - name: orders_id
        description: Primary key.
      - name: margin
        description: Margin = Revenue - Purchase_cost.
      - name: purchase_cost
        description: Purchase_cost = Quantity * Purchase_price.
      - name: date_date
        description: Date of the order.
      - name: revenue
        description: Sum of revenue per order.
      - name: quantity
        description: Sum of quantity per order.

  - name: int_orders_operational
    description: Operational margin calculation per order.
    columns:
      - name: operational_margin
        description: Operational margin = margin + shipping_fee - log_cost - ship_cost.

  - name: finance_days
    description: Finance calculation per day.
